version: "3.9"
services:
  postgres:
    image: postgres:14.2
    restart: always
    ports:
     - 5432:5432
    environment:
      - PGDATA=$HOME/postgresql/data
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data